services:
  localstack-gerencia-envio:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-gerencia-envio}"
    image: localstack/localstack
    ports:
      - "4569:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=sqs
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:4569
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-aws:/etc/localstack/init/ready.d"

  db-envio:
    image: postgres:13
    container_name: postgres-db-envio
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: envio
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - backend

  app-gerenciamento-envio:
    build:
      context: ..
      dockerfile: ./Dockerfile
    container_name: spring-boot-app-gerencia-envio
    ports:
      - "8083:8080"
    depends_on:
      - localstack-gerencia-envio
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: