apiVersion: v1
kind: ConfigMap
metadata:
  name: gerencia-envio-configmap
  namespace: hackathon-fiap
data:
  sqs_url: "https://sqs.us-east-1.amazonaws.com"
  db_url: "{{DB_URL}}"
  db_username: "{{DB_USERNAME}}"
  db_password: "{{DB_PASSWORD}}"
  aws_access_key: "{{AWS_ACCESS_KEY_ID}}"
  aws_secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
  aws_session_token: "{{AWS_SESSION_TOKEN}}"
